### ISSUE TITLE
Links all don't work

### ISSUE THREAD

**Issue by zackkatz** [gravityview/Admin-Views#1]
- [x] Link to single entry
- [x] Form action for the search bar
- [x] Pagination links

**Comment by soulseekah** [comment]
- [ ] Duplicate link
 - [ ] Edit link
 - [ ] Delete link

**Comment by soulseekah** [comment]
There are several other important prerequisite issues and initial warnings and bugs that require handling as part of this issue. Will be committing against it.

**Comment by soulseekah** [comment]
- [ ] Go back link

**Comment by soulseekah** [comment]
All fixes contingent on `feature/adminviews-1` branch in core.

**Comment by zackkatz** [comment]
@soulseekah i don’t see it; have you pushed?

**Comment by zackkatz** [comment]
- [ ] Linking to Edit Entry from the Multiple Entries screen doesn't work

**Comment by soulseekah** [comment]
>     * [ ]  Linking to Edit Entry from the Multiple Entries screen doesn't work (uses old permalink structure)

https://github.com/gravityview/Admin-Views/issues/1#issuecomment-565721462 this comment has Edit as a todo, which I'm working on currently. Is this something else?

**Comment by zackkatz** [comment]
@soulseekah The Link to edit from the multiple entries screen uses the front end permalink structure, instead of the permalink overrode override `/wp-admin/edit.php/entry/123/?post_type=gravityview[...]&edit=ajdheh`

**Comment by soulseekah** [comment]
- [ ] Custom content merge tags

**Comment by soulseekah** [comment]
Having a tough time with Notes and Approve fields at the moment. Will switch to something different and return to this next week, if you don't mind.

**Comment by soulseekah** [comment]
We should be done with this issue now.
Any new issues discovered should be created anew.
Thank you.
