### ISSUE TITLE
Delete Entry link does not redirect to Multiple Entries correctly

### ISSUE THREAD

**Issue by zackkatz** [gravityview/Admin-Views#14]
1. Add a Delete Entry field to a View
2. Have ["Redirect to Multiple Entries" as the View setting](https://i.gravitykit.com/i/XRtiS5)
3. Visit the View in the Dashboard
4. Click the Delete Entry link

**What happens:**
Entry redirects to CPT page (`https://example.com/wp-admin/edit.php?post_type=gravityview`)

**What should happen:**
Entry redirects to Multiple Entries context: (`https://example.com/wp-admin/edit.php?post_type=gravityview&page=dashboard_views&gvid=10990`)

**Comment by mrcasual** [comment]
Fixed in 3037a43.
